---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podcounter
spec:
  selector:
    matchLabels:
      app: podcounter
  replicas: 1
  template:
    metadata:
      labels:
        app: podcounter
    spec:
      serviceAccountName: podcounter
      containers:
      - name: podcounter
        image: tkhalil/podcounter:latest
