---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: podcounter
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: podreader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["khalilt.com"]
  resources: ["podcounters"]
  verbs: ["get", "list", "create", "patch", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: podcounter
  namespace: default
subjects:
- kind: ServiceAccount
  name: podcounter
  namespace: default
roleRef:
  kind: ClusterRole
  name: podreader
  apiGroup: rbac.authorization.k8s.io
