/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	podcounter_v1 "github.com/bitshifta/crd-controller/pkg/apis/podcounter/v1"
	versioned "github.com/bitshifta/crd-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/bitshifta/crd-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/bitshifta/crd-controller/pkg/client/listers/podcounter/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PodCounterInformer provides access to a shared informer and lister for
// PodCounters.
type PodCounterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.PodCounterLister
}

type podCounterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPodCounterInformer constructs a new informer for PodCounter type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPodCounterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPodCounterInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPodCounterInformer constructs a new informer for PodCounter type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPodCounterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KhaliltV1().PodCounters(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KhaliltV1().PodCounters(namespace).Watch(options)
			},
		},
		&podcounter_v1.PodCounter{},
		resyncPeriod,
		indexers,
	)
}

func (f *podCounterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPodCounterInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *podCounterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&podcounter_v1.PodCounter{}, f.defaultInformer)
}

func (f *podCounterInformer) Lister() v1.PodCounterLister {
	return v1.NewPodCounterLister(f.Informer().GetIndexer())
}
