/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	podcounter_v1 "github.com/bitshifta/crd-controller/pkg/apis/podcounter/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePodCounters implements PodCounterInterface
type FakePodCounters struct {
	Fake *FakeKhaliltV1
	ns   string
}

var podcountersResource = schema.GroupVersionResource{Group: "khalilt.com", Version: "v1", Resource: "podcounters"}

var podcountersKind = schema.GroupVersionKind{Group: "khalilt.com", Version: "v1", Kind: "PodCounter"}

// Get takes name of the podCounter, and returns the corresponding podCounter object, and an error if there is any.
func (c *FakePodCounters) Get(name string, options v1.GetOptions) (result *podcounter_v1.PodCounter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(podcountersResource, c.ns, name), &podcounter_v1.PodCounter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*podcounter_v1.PodCounter), err
}

// List takes label and field selectors, and returns the list of PodCounters that match those selectors.
func (c *FakePodCounters) List(opts v1.ListOptions) (result *podcounter_v1.PodCounterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(podcountersResource, podcountersKind, c.ns, opts), &podcounter_v1.PodCounterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &podcounter_v1.PodCounterList{ListMeta: obj.(*podcounter_v1.PodCounterList).ListMeta}
	for _, item := range obj.(*podcounter_v1.PodCounterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested podCounters.
func (c *FakePodCounters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(podcountersResource, c.ns, opts))

}

// Create takes the representation of a podCounter and creates it.  Returns the server's representation of the podCounter, and an error, if there is any.
func (c *FakePodCounters) Create(podCounter *podcounter_v1.PodCounter) (result *podcounter_v1.PodCounter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(podcountersResource, c.ns, podCounter), &podcounter_v1.PodCounter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*podcounter_v1.PodCounter), err
}

// Update takes the representation of a podCounter and updates it. Returns the server's representation of the podCounter, and an error, if there is any.
func (c *FakePodCounters) Update(podCounter *podcounter_v1.PodCounter) (result *podcounter_v1.PodCounter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(podcountersResource, c.ns, podCounter), &podcounter_v1.PodCounter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*podcounter_v1.PodCounter), err
}

// Delete takes name of the podCounter and deletes it. Returns an error if one occurs.
func (c *FakePodCounters) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(podcountersResource, c.ns, name), &podcounter_v1.PodCounter{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePodCounters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(podcountersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &podcounter_v1.PodCounterList{})
	return err
}

// Patch applies the patch and returns the patched podCounter.
func (c *FakePodCounters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *podcounter_v1.PodCounter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(podcountersResource, c.ns, name, data, subresources...), &podcounter_v1.PodCounter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*podcounter_v1.PodCounter), err
}
